name: ldsw_utilizacion_de_widgets
description: >
  Aplicación Flutter que muestra un catálogo de películas usando los widgets
  Text, Row, Column, Stack y Container.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter

  shared_preferences: ^2.0.15  

  # Iconos de Material (ya incluidos con Flutter)
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets: 
    - assets/images/cine_bg.jpg

